[package]
name = "crablit"
description = "A cli learning app using spaced repetition."
authors = ["Jeromos Kovács <iitsnotme214@protonmail.com>"]
version = "0.1.3"
edition = "2021"
homepage = "https://github.com/JeromeSchmied/crablit"
repository = "https://github.com/JeromeSchmied/crablit"
readme = "README.md"
license = "MIT"
keywords = [
  "srs",
  "cli",
  "vocabulary-learning",
  "language-learning",
  "flashcards",
]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# to collect arguments
clap = { version = "4.4.8", features = ["derive"] }
# for colored output
colored = "2.0"
# for shuffling deck
nanorand = "0.7.0"
# for editable input
rustyline = "12.0.0"
