[package]
name = "flashcards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# for clearing screen
clearscreen = "*"
# for colored output
colored = "2.0"
# for shuffling questions
rand = "*"
