[package]
name = "crablit"
description = "A cli learning app using spaced repetition, inspired by anki, quizlet, knowt."
authors = ["Jeromos Kovács <iitsnotme214@protonmail.com>"]
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/JeromeSchmied/crablit"
repository = "https://github.com/JeromeSchmied/crablit"
readme = "README.md"
license = "MIT"
keywords = [
  "srs",
  "cli",
  "vocabulary-learning",
  "language-learning",
  "flashcards",
]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# clap = "4.4.7"
# for clearing screen, currently not used
# clearscreen = "*"
# for colored output
colored = "2.0"
# for shuffling questions
rand = "0.8.5"
